name: Android CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug APK
      run: bash ./gradlew assembleDebug
    - name: Upload edbug APK 
      uses: actions/upload-artifact@v2
      with:
        name: App-debug
        path: ./app/build/outputs/apk/debug/app-debug.apk
